version: '3.9'

services:
  # And put them in an OTEL collector pipeline...
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.multitenant.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"     #otlp GRPC

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data/:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4317"        #otlp GRPC

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch tempoBackendSearch
    ports:
      - "3000:3000"